import pandas as pd
import os
from datetime import datetime

class ReportGenerator:
    def __init__(self, results_df: pd.DataFrame, save_dir: str, experiment_name: str):
        self.df = results_df
        self.save_dir = save_dir
        self.experiment_name = experiment_name
        os.makedirs(self.save_dir, exist_ok=True)

    def _calculate_metrics(self):
        metrics = []
        for opt_name, group in self.df.groupby('optimizer'):
            final_loss = group['loss'].iloc[-1]
            total_time = group['step_time_ms'].sum() / 1000.0 # в секунды
            
            # Считаем итерацию, на которой loss стал меньше 110% от финального
            # (Приближение "скорости сходимости" из нашего Proposal)
            target_loss = final_loss * 1.10
            converged_at = group[group['loss'] <= target_loss]['iteration'].iloc[0]
            
            metrics.append({
                'Optimizer': opt_name,
                'Final Loss': f"{final_loss:.4f}",
                'Convergence Iter': converged_at,
                'Total Time (s)': f"{total_time:.2f}"
            })
        return pd.DataFrame(metrics)

    def generate_html(self):
        metrics_df = self._calculate_metrics()
        
        # Проверяем наличие картинок
        loss_img = "loss_curves.png" if os.path.exists(os.path.join(self.save_dir, "loss_curves.png")) else ""
        traj_img = "trajectories_2d.png" if os.path.exists(os.path.join(self.save_dir, "trajectories_2d.png")) else ""

        html_content = f"""
        <!DOCTYPE html>
        <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <title>OptiBench Report: {self.experiment_name}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7f6; color: #333; margin: 0; padding: 20px; }}
                .container {{ max-width: 1000px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                h2 {{ color: #2980b9; margin-top: 30px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #f8f9fa; font-weight: bold; }}
                tr:hover {{ background-color: #f1f1f1; }}
                .img-container {{ text-align: center; margin-top: 20px; }}
                img {{ max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 4px; padding: 5px; }}
                .footer {{ margin-top: 40px; text-align: center; font-size: 0.9em; color: #7f8c8d; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>OptiBench Report</h1>
                <p><strong>Experiment:</strong> {self.experiment_name}</p>
                <p><strong>Date generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

                <h2>Performance Metrics</h2>
                {metrics_df.to_html(index=False, classes='table', border=0)}

                <h2>Visualizations</h2>
        """
        
        if traj_img:
            html_content += f"""
                <div class="img-container">
                    <h3>Optimization Trajectories (2D)</h3>
                    <img src="{traj_img}" alt="2D Trajectories">
                </div>
            """
            
        if loss_img:
            html_content += f"""
                <div class="img-container">
                    <h3>Convergence Curves</h3>
                    <img src="{loss_img}" alt="Loss Curves">
                </div>
            """

        html_content += """
            </div>
            <div class="footer">Generated by OptiBench Library (MIT Project)</div>
        </body>
        </html>
        """

        report_path = os.path.join(self.save_dir, 'report.html')
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"[Report] Generated HTML report at: {report_path}")
