experiment_name: "rosenbrock_test"
seed: 42
device: "cpu"

problem:
  name: "rosenbrock"
  dimensions: 2
  init_theta: [-2.0, 2.0] # Начальная точка для наглядной траектории

optimizers:
  - name: "SGD"
    params: {lr: 0.001, momentum: 0.9}
  - name: "Adam"
    params: {lr: 0.1}
  - name: "RMSprop"
    params: {lr: 0.05, alpha: 0.99}

training:
  iterations: 500
  log_interval: 1

output:
  log_format: "csv"
  save_dir: "./results/rosenbrock_test/"
